"""Description

Revision ID: ceef7d5c8f1f
Revises: aef07c3194ce
Create Date: 2023-12-01 02:05:24.372411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceef7d5c8f1f'
down_revision = 'aef07c3194ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('execution_order')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_order', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
